mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
    mapper-locations: classpath:com/rg/cmsservice/mapper/xml/*.xml #配置mapper xml文件的路径
server:
    port: 8004
spring:
    application:
        name: service-cms
    datasource: # mysql数据库连接
        driver-class-name: com.mysql.jdbc.Driver
        password: 186259
        url: jdbc:mysql://localhost:3306/guli_edu
        username: root
    jackson: #返回json的全局时间格式
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

    cloud: #nacos服务地址
        nacos:
            discovery:
                server-addr: 192.168.174.128:8848
    redis: #redis相关配置
        host: 192.168.174.128
        port: 6379
        database: 0
        timeout: 1800000
        lettuce: #最大阻塞等待时间
            pool:
                max-active: 20
                max-wait: -1
                max-idle: 5
                min-idle: 0