#mybatis-plus: #mybatis配置
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    mapper-locations: classpath:com/rg/smsservice/mapper/xml/*.xml
server: #服务端口
    port: 8005
spring:
    application: #服务名称
        name: service-msm
    jackson: #Json格式
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    redis: #redis配置
        database: 0
        host: 192.168.174.128
        lettuce:
            pool:
                max-active: 20
                max-idle: 5
                max-wait: -1
                min-idle: 0
        port: 6379
        timeout: 1800000
    #nacos服务地址
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.174.128:8848
#国阳云短信服务
gyyun:
  sms:
    appCode: c65ad05f5bb84ed582bc3eea030fcf2e
    smsSignId: ece24562ed4b4c2695ee546752b7d293
    templateId: a09602b817fd47e59e7c6e603d3f088d
